### 1. 查看数据

In [9]:
import pandas as pd

pd.set_option("display.max_columns", None)  # 打印时显示所有的列

path = (
    r"C:\Users\Anderson\Desktop\RethinkFun深度学习\第七章  - 逻辑回归\titanic\train.csv"
)

df = pd.read_csv(path)

df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

| 列名 | 含义说明 |
|---|---|
| PassengerId | 乘客的唯一编号（标识符），每位乘客对应一个 ID |
| Survived | 是否生还（0 = 没有生还，1 = 生还） |
| Pclass | 舱位等级（1 = 一等舱，2 = 二等舱，3 = 三等舱） |
| Name | 乘客姓名 |
| Sex | 性别（male = 男，female = 女） |
| Age | 年龄（单位：岁，部分为空表示未知） |
| SibSp | 同船的兄弟姐妹或配偶的数量（Siblings/Spouses Aboard） |
| Parch | 同船的父母或子女的数量（Parents/Children Aboard） |
| Ticket | 船票号码 |
| Fare | 船票价格（单位：英镑） |
| Cabin | 舱位号（可能缺失） |
| Embarked | 登船港口（C = Cherbourg，Q = Queenstown，S = Southampton） |

### 2. 查看数据缺失情况

In [10]:
# 缺失比例
missing_rate = df.isna().mean().sort_values(ascending=False)
missing_rate * 100

Cabin          77.104377
Age            19.865320
Embarked        0.224467
PassengerId     0.000000
Name            0.000000
Pclass          0.000000
Survived        0.000000
Sex             0.000000
Parch           0.000000
SibSp           0.000000
Fare            0.000000
Ticket          0.000000
dtype: float64

In [11]:
# 缺失值
df.isna().sum().sort_values(ascending=False)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
Pclass           0
Survived         0
Sex              0
Parch            0
SibSp            0
Fare             0
Ticket           0
dtype: int64

### 3. 删除不必要的列

In [12]:
drop_cols = ["PassengerId", "Name", "Ticket", "Cabin"]
df = df.drop(columns=drop_cols)

df.head(5)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

### 4. 删除有年龄和登船港口缺失的样本

In [13]:
df = df.dropna(subset=["Age", "Embarked"])

df.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

### 5. 独热编码

In [14]:
df = pd.get_dummies(df, columns=["Sex", "Embarked"], drop_first=True, dtype=int)

df.head(5)

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,1,0,1
1,1,1,38.0,1,0,71.2833,0,0,0
2,1,3,26.0,0,0,7.9250,0,0,1
3,1,1,35.0,1,0,53.1000,0,0,1
4,0,3,35.0,0,0,8.0500,1,0,1